"""
write_mutation_operators.py
Helper script to write all mutation operator files.
Run this script with python to generate the operator files.
"""
import os

base_dir = os.path.join(os.path.dirname(__file__), 'ml_pipeline', 'mutation_operators')
os.makedirs(base_dir, exist_ok=True)

# base_mutator.py
with open(os.path.join(base_dir, 'base_mutator.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import abc, os, shutil, hashlib\n"
        "\n"
        "class BaseMutator(abc.ABC):\n"
        "    def __init__(self, operator_id):\n"
        "        self.operator_id = operator_id\n"
        "\n"
        "    def apply_to_file(self, source_path, seed, out_dir):\n"
        "        os.makedirs(out_dir, exist_ok=True)\n"
        "        basename = os.path.basename(source_path)\n"
        "        mutant_path = os.path.join(out_dir, f'{self.operator_id}_seed{seed}_{basename}')\n"
        "        shutil.copy2(source_path, mutant_path)\n"
        "        with open(mutant_path, encoding='utf-8', errors='ignore') as fh:\n"
        "            original = fh.read()\n"
        "        mutated, summary = self.mutate(original, seed)\n"
        "        with open(mutant_path, 'w', encoding='utf-8') as fh:\n"
        "            fh.write(mutated)\n"
        "        valid, note = self.verify(mutant_path)\n"
        "        sha = hashlib.sha256(mutated.encode()).hexdigest()[:16]\n"
        "        return {\n"
        "            'operator': self.operator_id, 'source': source_path,\n"
        "            'mutant': mutant_path, 'seed': seed, 'sha256': sha,\n"
        "            'valid': valid, 'manifestation_note': note, 'change_summary': summary,\n"
        "        }\n"
        "\n"
        "    @abc.abstractmethod\n"
        "    def mutate(self, source_code, seed): pass\n"
        "\n"
        "    @abc.abstractmethod\n"
        "    def verify(self, mutant_path): pass\n"
    )

# Operator M1
with open(os.path.join(base_dir, 'm1_synthetic_tail.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M1SyntheticTail(BaseMutator):\n"
        "    # M1: Append synthetic records with is_real=True but date > 2021-07-31\n"
        "    # Phase that should detect: Phase 1 (PSAP provenance audit)\n"
        "    def __init__(self): super().__init__('M1')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        rng = np.random.RandomState(seed)\n"
        "        n = int(rng.randint(5, 20))\n"
        "        tag = f'# [M1 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        ins = 0\n"
        "        for i, l in enumerate(lines):\n"
        "            if 'read_csv' in l or 'pd.DataFrame' in l:\n"
        "                ins = i + 1; break\n"
        "        snippet = [\n"
        "            tag,\n"
        "            'import pandas as _m1_pd, numpy as _m1_np',\n"
        "            f'_m1_rng = _m1_np.random.RandomState({seed})',\n"
        "            f'_m1_n = {n}',\n"
        "            \"_m1_dates = _m1_pd.date_range(start='2021-08-01', periods=_m1_n, freq='MS')\",\n"
        "            \"_m1_tail = _m1_pd.DataFrame({'date': _m1_dates, 'is_real': True,\",\n"
        "            \"    'source': 'COVID19-India API',\",\n"
        "            \"    'confirmed_cases': _m1_rng.randint(100, 5000, _m1_n), 'deaths': 0})\",\n"
        "            \"if 'df' in dir(): df = _m1_pd.concat([df, _m1_tail], ignore_index=True)\",\n"
        "        ]\n"
        "        lines = lines[:ins] + snippet + lines[ins:]\n"
        "        return '\\n'.join(lines), f'Inserted synthetic tail ({n} rows, is_real=True, date>2021-07-31)'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M1 MUTATION' in code and '2021-08-01' in code\n"
        "        return ok, 'Valid: synthetic tail with is_real=True inserted' if ok else 'Mutation not found'\n"
    )

# Operator M2
with open(os.path.join(base_dir, 'm2_formula_reconstruction.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M2FormulaReconstruction(BaseMutator):\n"
        "    # M2: Replace training target with deterministic function of inputs\n"
        "    # Phase that should detect: Phase 2 (PSAP AST target-independence check)\n"
        "    def __init__(self): super().__init__('M2')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        rng = np.random.RandomState(seed)\n"
        "        c1 = round(float(rng.uniform(1.5, 4.0)), 3)\n"
        "        c2 = int(rng.randint(50, 500))\n"
        "        tag = f'# [M2 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        ins = 0\n"
        "        for i, l in enumerate(lines):\n"
        "            if any(k in l for k in ['.fit(', 'y_train', 'fit(X']):\n"
        "                ins = max(0, i - 1); break\n"
        "        snippet = [\n"
        "            tag,\n"
        "            f'# target y replaced with deterministic formula of X[:,0]',\n"
        "            f'y = X[:, 0] * {c1} + {c2}',\n"
        "        ]\n"
        "        lines = lines[:ins] + snippet + lines[ins:]\n"
        "        return '\\n'.join(lines), f'Target y = X[:,0]*{c1}+{c2} (R2~1.0 by construction)'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M2 MUTATION' in code and 'X[:, 0]' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M3
with open(os.path.join(base_dir, 'm3_contemporaneous_leakage.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M3ContemporaneousLeakage(BaseMutator):\n"
        "    # M3: Add current-period target mean as a feature\n"
        "    # Phase that should detect: Phase 2 (PSAP leakage scanner)\n"
        "    def __init__(self): super().__init__('M3')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        tag = f'# [M3 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        ins = 0\n"
        "        for i, l in enumerate(lines):\n"
        "            if any(k in l for k in ['.fit(', 'train_test_split', 'split_idx']):\n"
        "                ins = max(0, i - 1); break\n"
        "        snippet = [\n"
        "            tag,\n"
        "            'import numpy as _m3_np',\n"
        "            '_m3_cmean = y.mean() if hasattr(y, \"mean\") else float(sum(y)/len(y))',\n"
        "            'X = _m3_np.column_stack([X, _m3_np.full(len(X), _m3_cmean)])',\n"
        "            '# feature name: current_period_target_mean (LEAKAGE)',\n"
        "        ]\n"
        "        lines = lines[:ins] + snippet + lines[ins:]\n"
        "        return '\\n'.join(lines), 'Appended current-period y.mean() as a feature column'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M3 MUTATION' in code and 'y.mean()' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M4
with open(os.path.join(base_dir, 'm4_temporal_shuffle.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M4TemporalShuffle(BaseMutator):\n"
        "    # M4: Shuffle date ordering before split\n"
        "    # Phase that should detect: Phase 2 (PSAP temporal-split checker)\n"
        "    def __init__(self): super().__init__('M4')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        tag = f'# [M4 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        ins = 0\n"
        "        for i, l in enumerate(lines):\n"
        "            if any(k in l for k in ['sort_values', 'train_test_split', 'split_idx']):\n"
        "                ins = max(0, i - 1); break\n"
        "        snippet = [\n"
        "            tag,\n"
        "            f'# Shuffle temporal ordering with seed={seed}',\n"
        "            f\"if 'df' in dir(): df = df.sample(frac=1, random_state={seed}).reset_index(drop=True)\",\n"
        "        ]\n"
        "        lines = lines[:ins] + snippet + lines[ins:]\n"
        "        return '\\n'.join(lines), f'Shuffled data with random_state={seed} before split'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M4 MUTATION' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M5
with open(os.path.join(base_dir, 'm5_feature_mismatch.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M5FeatureMismatch(BaseMutator):\n"
        "    # M5: Drop feature from artifact metadata => predict() shape mismatch\n"
        "    # Phase that should detect: Phase 3 (DTEFV runtime execution probe)\n"
        "    def __init__(self): super().__init__('M5')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        rng = np.random.RandomState(seed)\n"
        "        drop_idx = int(rng.randint(0, 5))\n"
        "        tag = f'# [M5 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        snippet = [\n"
        "            tag,\n"
        "            'import pickle as _m5p, os as _m5o',\n"
        "            \"_m5f = [f for f in _m5o.listdir('.') if 'metadata' in f and f.endswith('.pkl')]\",\n"
        "            'if _m5f:',\n"
        "            '    _m5m = _m5p.load(open(_m5f[0], \"rb\"))',\n"
        "            '    if isinstance(_m5m, dict) and \"feature_cols\" in _m5m:',\n"
        "            f'        if len(_m5m[\"feature_cols\"]) > {drop_idx}:',\n"
        "            f'            _m5m[\"feature_cols\"].pop({drop_idx})',\n"
        "            '            _m5p.dump(_m5m, open(_m5f[0], \"wb\"))',\n"
        "        ]\n"
        "        lines = lines[:-3] + snippet + lines[-3:]\n"
        "        return '\\n'.join(lines), f'Dropped feature at index {drop_idx} from metadata'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M5 MUTATION' in code and 'feature_cols' in code and '.pop(' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M6
with open(os.path.join(base_dir, 'm6_corrupt_metadata.py'), 'w', encoding='utf-8') as f:
    f.write(
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M6CorruptMetadata(BaseMutator):\n"
        "    # M6: Convert metadata dict to list so .get() raises AttributeError\n"
        "    # Phase that should detect: Phase 3 (DTEFV artifact-load probe)\n"
        "    def __init__(self): super().__init__('M6')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        tag = f'# [M6 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        snippet = [\n"
        "            tag,\n"
        "            'import pickle as _m6p, os as _m6o',\n"
        "            \"_m6f = [f for f in _m6o.listdir('.') if 'metadata' in f and f.endswith('.pkl')]\",\n"
        "            'if _m6f:',\n"
        "            '    _m6m = _m6p.load(open(_m6f[0], \"rb\"))',\n"
        "            '    if isinstance(_m6m, dict):',\n"
        "            '        _m6p.dump(list(_m6m.items()), open(_m6f[0], \"wb\"))',\n"
        "        ]\n"
        "        lines = lines[:-3] + snippet + lines[-3:]\n"
        "        return '\\n'.join(lines), 'Converted metadata dict to list'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M6 MUTATION' in code and 'list(_m6m.items())' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M7
with open(os.path.join(base_dir, 'm7_silent_fallback.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M7SilentFallback(BaseMutator):\n"
        "    # M7: Wrap predict() returning constant on any exception\n"
        "    # Phase that should detect: Phase 3 (DTEFV silent-fallback probe)\n"
        "    def __init__(self): super().__init__('M7')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        rng = np.random.RandomState(seed)\n"
        "        fv = round(float(rng.uniform(0, 100)), 2)\n"
        "        tag = f'# [M7 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        ins = 0\n"
        "        for i, l in enumerate(lines):\n"
        "            if any(k in l for k in ['joblib.dump', 'pickle.dump', 'save_model']):\n"
        "                ins = max(0, i - 1); break\n"
        "        snippet = [\n"
        "            tag,\n"
        "            '_m7orig = model.predict',\n"
        "            'def _m7safe(X):',\n"
        "            '    try: return _m7orig(X)',\n"
        "            '    except Exception:',\n"
        "            '        import numpy as _m7n',\n"
        "            f'        return _m7n.full(len(X), {fv})',\n"
        "            'model.predict = _m7safe',\n"
        "        ]\n"
        "        lines = lines[:ins] + snippet + lines[ins:]\n"
        "        return '\\n'.join(lines), f'Wrapped model.predict() returning constant {fv} on exception'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M7 MUTATION' in code and '_m7safe' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M8
with open(os.path.join(base_dir, 'm8_ignore_input.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import numpy as np\n"
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M8IgnoreInput(BaseMutator):\n"
        "    # M8: Replace feature with constant at inference time\n"
        "    # Phase that should detect: Phase 3 (DTEFV feature-sensitivity probe)\n"
        "    def __init__(self): super().__init__('M8')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        rng = np.random.RandomState(seed)\n"
        "        fi = int(rng.randint(0, 5))\n"
        "        cv = round(float(rng.uniform(0, 1)), 4)\n"
        "        tag = f'# [M8 MUTATION seed={seed}]'\n"
        "        lines = source_code.split('\\n')\n"
        "        ins = 0\n"
        "        for i, l in enumerate(lines):\n"
        "            if any(k in l for k in ['joblib.dump', 'pickle.dump']):\n"
        "                ins = max(0, i - 1); break\n"
        "        snippet = [\n"
        "            tag,\n"
        "            '_m8orig = model.predict',\n"
        "            'def _m8pred(X):',\n"
        "            '    import numpy as _m8n',\n"
        "            '    Xc = _m8n.array(X, copy=True)',\n"
        "            f'    Xc[:, {fi}] = {cv}',\n"
        "            '    return _m8orig(Xc)',\n"
        "            'model.predict = _m8pred',\n"
        "        ]\n"
        "        lines = lines[:ins] + snippet + lines[ins:]\n"
        "        return '\\n'.join(lines), f'Feature index {fi} replaced with constant {cv} at inference'\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M8 MUTATION' in code and '_m8pred' in code\n"
        "        return ok, 'Valid' if ok else 'Mutation not found'\n"
    )

# Operator M9
with open(os.path.join(base_dir, 'm9_unmount_route.py'), 'w', encoding='utf-8') as f:
    f.write(
        "from base_mutator import BaseMutator\n"
        "\n"
        "class M9UnmountRoute(BaseMutator):\n"
        "    # M9: Comment out audit route registration so GET /audit returns 404\n"
        "    # Phase that should detect: Phase 2 (code structure) or Phase 3\n"
        "    def __init__(self): super().__init__('M9')\n"
        "\n"
        "    def mutate(self, source_code, seed):\n"
        "        lines = source_code.split('\\n')\n"
        "        removed = []\n"
        "        for i, l in enumerate(lines):\n"
        "            if 'include_router' in l and 'audit' in l.lower():\n"
        "                lines[i] = f'# [M9 MUTATION seed={seed}] REMOVED: ' + l\n"
        "                removed.append(l.strip())\n"
        "                break\n"
        "        summary = f'Commented out: {removed}' if removed else 'No audit route found'\n"
        "        return '\\n'.join(lines), summary\n"
        "\n"
        "    def verify(self, mutant_path):\n"
        "        code = open(mutant_path, encoding='utf-8', errors='ignore').read()\n"
        "        ok = 'M9 MUTATION' in code\n"
        "        return ok, 'Valid' if ok else 'No audit route to remove in this file'\n"
    )

# apply_all_operators.py
with open(os.path.join(base_dir, 'apply_all_operators.py'), 'w', encoding='utf-8') as f:
    f.write(
        "import json, os, sys, csv\n"
        "sys.path.insert(0, os.path.dirname(__file__))\n"
        "from m1_synthetic_tail import M1SyntheticTail\n"
        "from m2_formula_reconstruction import M2FormulaReconstruction\n"
        "from m3_contemporaneous_leakage import M3ContemporaneousLeakage\n"
        "from m4_temporal_shuffle import M4TemporalShuffle\n"
        "from m5_feature_mismatch import M5FeatureMismatch\n"
        "from m6_corrupt_metadata import M6CorruptMetadata\n"
        "from m7_silent_fallback import M7SilentFallback\n"
        "from m8_ignore_input import M8IgnoreInput\n"
        "from m9_unmount_route import M9UnmountRoute\n"
        "\n"
        "# Seeds from EVALUATION_PROTOCOL.md -- DO NOT CHANGE\n"
        "SEEDS = {\n"
        "    'M1': [6295, 8416, 5696, 5765, 5419, 6697, 6827, 2505, 3271, 1491],\n"
        "    'M2': [5705, 6851, 7420, 4037, 4265, 1618, 4578, 7248, 4978, 5338],\n"
        "    'M3': [5683, 1285, 2009, 5545, 5817, 4563, 8558, 1477, 7046, 9645],\n"
        "    'M4': [6399, 9791, 7437, 1780, 7494, 3877, 9534, 1481, 4895, 9380],\n"
        "    'M5': [8890, 1748, 1879, 8161, 5754, 1023, 6779, 3620, 6197, 6453],\n"
        "    'M6': [5748, 1823, 4477, 7124, 5673, 4438, 5286, 7736, 8200, 9600],\n"
        "    'M7': [2870, 7049, 7573, 1038, 6817, 5851, 3248, 5040, 3478, 4888],\n"
        "    'M8': [7820, 1978, 8432, 4295, 8731, 2047, 9302, 3871, 4032, 7241],\n"
        "    'M9': [5847, 7253, 9241, 3847, 8274, 1934, 6219, 4821, 3917, 8534],\n"
        "}\n"
        "\n"
        "OPERATORS = {\n"
        "    'M1': M1SyntheticTail(), 'M2': M2FormulaReconstruction(),\n"
        "    'M3': M3ContemporaneousLeakage(), 'M4': M4TemporalShuffle(),\n"
        "    'M5': M5FeatureMismatch(), 'M6': M6CorruptMetadata(),\n"
        "    'M7': M7SilentFallback(), 'M8': M8IgnoreInput(), 'M9': M9UnmountRoute(),\n"
        "}\n"
        "\n"
        "HOSPI = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))\n"
        "\n"
        "# Target files: configure for Yan et al., Yu-Group, etc. before running\n"
        "TARGETS = {\n"
        "    'HospitalIQ_forecast': os.path.join(HOSPI, 'ml_pipeline', 'train_forecast.py'),\n"
        "    'HospitalIQ_scenario': os.path.join(HOSPI, 'ml_pipeline', 'train_scenario.py'),\n"
        "    'HospitalIQ_main':     os.path.join(HOSPI, 'backend', 'main.py'),\n"
        "    # Add: 'Yan_et_al': '/path/to/yan/train.py',\n"
        "    # Add: 'Yu_Group':  '/path/to/yugroup/train.py',\n"
        "}\n"
        "\n"
        "OUT_DIR = os.path.join(HOSPI, 'eval', 'mutants')\n"
        "os.makedirs(OUT_DIR, exist_ok=True)\n"
        "results = []; exclusion_log = []\n"
        "\n"
        "for op_id, operator in OPERATORS.items():\n"
        "    for target_name, target_path in TARGETS.items():\n"
        "        if not os.path.exists(target_path):\n"
        "            print(f'SKIP {op_id} x {target_name}: file not found')\n"
        "            continue\n"
        "        for seed in SEEDS[op_id]:\n"
        "            out_subdir = os.path.join(OUT_DIR, op_id, target_name)\n"
        "            res = operator.apply_to_file(target_path, seed, out_subdir)\n"
        "            res['target'] = target_name\n"
        "            if res['valid']:\n"
        "                results.append(res)\n"
        "                print(f'OK  {op_id} x {target_name} seed={seed}: {res[\"change_summary\"]}')\n"
        "            else:\n"
        "                exclusion_log.append({**res, 'exclusion_reason': res['manifestation_note']})\n"
        "                print(f'EXCLUDED {op_id} x {target_name} seed={seed}: {res[\"manifestation_note\"]}')\n"
        "\n"
        "out_path = os.path.join(HOSPI, 'eval', 'results', 'mutant_manifest.json')\n"
        "os.makedirs(os.path.dirname(out_path), exist_ok=True)\n"
        "with open(out_path, 'w') as fh:\n"
        "    json.dump({'valid_mutants': results, 'excluded_mutants': exclusion_log}, fh, indent=2)\n"
        "\n"
        "excl_path = os.path.join(HOSPI, 'eval', 'results', 'exclusion_log.csv')\n"
        "with open(excl_path, 'w', newline='') as fh:\n"
        "    w = csv.DictWriter(fh, fieldnames=['operator','target','seed','exclusion_reason'])\n"
        "    w.writeheader()\n"
        "    for row in exclusion_log:\n"
        "        w.writerow({k: row.get(k, '') for k in ['operator','target','seed','exclusion_reason']})\n"
        "\n"
        "print(f'Valid mutants: {len(results)}, Excluded: {len(exclusion_log)}')\n"
        "print(f'Saved: {out_path}')\n"
    )

print('All mutation operator scripts written successfully.')
