# Real Indian districts for data generation
# Each state has at least 10 districts

STATE_DISTRICTS = {
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem",
                   "Tirunelveli", "Vellore", "Erode", "Thoothukudi", "Dindigul",
                   "Kancheepuram", "Virudhunagar"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik",
                    "Aurangabad", "Solapur", "Kolhapur", "Satara", "Sangli",
                    "Amravati", "Chandrapur"],
    "Delhi": ["Central Delhi", "South Delhi", "East Delhi", "North Delhi",
              "West Delhi", "New Delhi", "Shahdara", "North West Delhi"],
    "Karnataka": ["Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum",
                  "Gulbarga", "Davangere", "Shimoga", "Tumkur", "Udupi",
                  "Hassan", "Raichur"],
    "West Bengal": ["Kolkata", "Darjeeling", "Hooghly", "Howrah", "Bardhaman",
                    "Nadia", "Murshidabad", "Midnapore", "Jalpaiguri", "Cooch Behar",
                    "Bankura", "Birbhum"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner",
                  "Ajmer", "Alwar", "Bhilwara", "Sikar", "Bharatpur",
                  "Pali", "Jhunjhunu"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar",
                "Jamnagar", "Junagadh", "Gandhinagar", "Anand", "Navsari",
                "Surendranagar", "Bharuch"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Allahabad",
                      "Meerut", "Ghaziabad", "Noida", "Bareilly", "Aligarh",
                      "Moradabad", "Gorakhpur"],
    "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Alappuzha",
               "Kollam", "Palakkad", "Kannur", "Kottayam", "Malappuram",
               "Pathanamthitta", "Wayanad"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam",
                  "Ramagundam", "Mahbubnagar", "Nalgonda", "Adilabad", "Siddipet"],
    "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga",
              "Purnia", "Bihar Sharif", "Arrah", "Begusarai", "Chapra",
              "Katihar", "Munger"],
    "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain",
                       "Sagar", "Dewas", "Satna", "Ratlam", "Rewa",
                       "Murwara", "Singrauli"],
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool",
                       "Kakinada", "Rajahmundry", "Tirupati", "Anantapur", "Eluru",
                       "Ongole", "Kadapa"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur",
               "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar",
                  "Hazaribagh", "Giridih", "Ramgarh", "Dumka", "Phusro"],
    "Haryana": ["Chandigarh", "Faridabad", "Gurgaon", "Panipat", "Ambala",
                "Karnal", "Sonipat", "Yamunanagar", "Rohtak", "Hisar"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda",
               "Mohali", "Hoshiarpur", "Batala", "Pathankot", "Moga"],
    "Himachal Pradesh": ["Shimla", "Dharamshala", "Mandi", "Solan", "Kullu",
                         "Hamirpur", "Bilaspur", "Una", "Kangra", "Chamba"],
    "Uttarakhand": ["Dehradun", "Haridwar", "Rishikesh", "Haldwani", "Roorkee",
                    "Nainital", "Mussoorie", "Almora", "Pithoragarh", "Kotdwar"],
    "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda",
            "Bicholim", "Canacona", "Curchorem", "Valpoi", "Quepem"],
    "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon",
              "Tinsukia", "Bongaigaon", "Tezpur", "Goalpara", "Barpeta"],
    "Meghalaya": ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara",
                  "Williamnagar", "Resubelpara", "Mairang", "Nongpoh", "Amlarem"],
    "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati",
                "Ukhrul", "Tamenglong", "Chandel", "Jiribam", "Kakching"],
    "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib",
                "Lawngtlai", "Saiha", "Mamit", "Khawzawl", "Hnahthial"],
    "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha",
                 "Zunheboto", "Mon", "Phek", "Kiphire", "Longleng"],
    "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Belonia",
                "Khowai", "Ambassa", "Teliamura", "Kamalpur", "Sabroom"],
    "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo",
               "Singtam", "Jorethang", "Rhenock", "Pakyong", "Soreng"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Bomdila",
                          "Ziro", "Along", "Daporijo", "Tezu", "Anini"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg",
                     "Rajnandgaon", "Raigarh", "Jagdalpur", "Ambikapur", "Mahasamund"],
    "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Kathua",
                          "Sopore", "Udhampur", "Pulwama", "Rajouri", "Kupwara"],
}
